export { default as HomeLayout } from "./HomeLayout";
export { default as DashboardLayout } from "./DashboardLayout";
export { default as LandingPage } from "./LandingPage";
export { default as SignUpPage } from "./SignUpPage";
export { default as TeacherSignUpPage } from "./teacher/TeacherSignUpPage";
export { default as EmployerSignUpPage } from "./employer/EmployerSignUpPage";
export { default as SignInPage } from "./SignInPage";
// export { default as PrivateRoute } from "./PrivateRoute";
export { default as ProfileSetup } from "./ProfileSetup";
export { default as ManageAccountPage } from "./ManageAccountPage";
export { default as SuccessPage } from "./SuccessPage";
export { default as ProfilePage } from "./teacher/ProfilePage";
export { default as EmployerProfilePage } from "./employer/EmployerProfilePage";
export { default as HomePage } from "./teacher/HomePage";

export { default as ErrorPage } from "./ErrorPage";

export { default as SearchJob } from "./SearchJob";
export { default as AllJobs } from "./AllJobs";
export { default as AppHistory } from "./teacher/AppHistory";
export { default as Bookmarks } from "./teacher/Bookmarks";
export { default as GiveHiringTest } from "./teacher/GiveHiringTest";
export { default as EmployerHomePage } from "./employer/EmployerHomePage";
export { default as PostJobHome } from "./employer/PostJobHome";
export { default as PostJob } from "./employer/PostJob";
export { default as HiringTests } from "./employer/HiringTests";
export { default as AddHiringTest } from "./employer/AddHiringTest";
export { default as JobApplications } from "./employer/JobApplications";
export { default as JobApplicationCandidates } from "./employer/JobApplicationCandidates";
export { default as JobPage } from "./JobPage";
export { default as Notifications } from "./Notifications";
export { default as ViewTeacherProfile } from "./ViewTeacherProfile";
export { default as ViewEmployerProfilePage } from "./ViewEmployerProfilePage";

export { default as AdminDashboardLayout } from "./admin/AdminDashboardLayout";
export { default as AdminHomePage } from "./admin//AdminHomePage";
export { default as AdminManageJobsPage } from "./admin/AdminManageJobsPage";
export { default as AdminManageTeachersPage } from "./admin/AdminManageTeachersPage";
export { default as AdminManageEmployersPage } from "./admin/AdminManageEmployersPage";
export { default as AdminManageHiringTestsPage } from "./admin/AdminManageHiringTestsPage";
