const data = [
  {
    label: "Abdul Wali Khan University",
    "Established Since": "2/25/2009",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Mardan",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Aga Khan University",
    "Established Since": "3/2/1983",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Air University",
    "Established Since": "10/29/2002",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Air War College Institute, Karachi",
    "Established Since": "1/21/2021",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Al-Hamd Islamic University",
    "Established Since": "4/20/2005",
    Sector: "Private",
    "Chartered By": "Government of Balochistan",
    City: "Quetta",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "Ali Institute of Education",
    "Established Since": "2/15/2010",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Al-Karam International Institute, Bhera",
    "Established Since": "1/12/2021",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Bhera",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Al-Khair University",
    "Established Since": "7/4/1994",
    Sector: "Private",
    "Chartered By": "Government of AJK",
    City: "Bhimber",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "Allama Iqbal Open University",
    "Established Since": "7/5/1984",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Aror University of Art, Architecture, Design and Heritage, Sukkur",
    "Established Since": "7/15/2020",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Sukkur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Bacha Khan University",
    "Established Since": "3/7/2012",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Charsada",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Bahauddin Zakariya University",
    "Established Since": "3/4/1975",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Bahria University",
    "Established Since": "2/7/2000",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Balochistan University of Engineering & Technology",
    "Established Since": "8/3/1994",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Khuzdar",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label:
      "Balochistan University of Information Technology, Engineering & Management Sciences (BUITEMS)",
    "Established Since": "7/18/2002",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Quetta",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "Baqai Medical University",
    "Established Since": "5/26/1996",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Beaconhouse National University",
    "Established Since": "7/2/2005",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Begum Nustrat Bhutto Women University, Sukkur",
    "Established Since": "6/7/2018",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Sukkur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Benazir Bhutto Shaheed University Lyari",
    "Established Since": "1/28/2010",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label:
      "Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur Mirs",
    "Established Since": "4/22/2016",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Khairpur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Brains Institute Peshawar",
    "Established Since": "10/20/2016",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Capital University of Science & Technology",
    "Established Since": "9/28/2015",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "CECOS University of Information Technology & Emerging Sciences",
    "Established Since": "8/30/2001",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Cholistan University of Veterinary and Animal Sciences, Bahawalpur",
    "Established Since": "5/4/2018",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Bahawal Pur",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "City University of Science and Information Technology",
    "Established Since": "8/30/2001",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Commecs Institute of Business & Emerging Sciences",
    "Established Since": "2/18/2010",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "COMSATS Institute of Information Technology",
    "Established Since": "8/12/2000",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Dadabhoy Institute of Higher Education",
    "Established Since": "1/12/2004",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Dawood University of Engineering & Technology",
    "Established Since": "10/31/2007",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "DHA Suffa University",
    "Established Since": "5/27/2002",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "DOW University of Health Sciences",
    "Established Since": "12/17/2005",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Emaan Institute of Management & Sciences, Karachi",
    "Established Since": "5/28/2018",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Emerson University, Multan",
    "Established Since": "5/17/2021",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Faisalabad Medical University, Faisalabad",
    "Established Since": "9/28/2017",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Fatima Jinnah Medical University, Lahore",
    "Established Since": "7/1/2015",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Fatima Jinnah Women University, Rawalpindi",
    "Established Since": "8/9/1999",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Federal Urdu University of Arts, Sciences & Technology",
    "Established Since": "11/13/2002",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Forman Christian College",
    "Established Since": "10/12/2004",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Foundation University",
    "Established Since": "10/25/2002",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Gambat Institute of Medical Sciences",
    "Established Since": "12/18/2006",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Khairpur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Gandhara University",
    "Established Since": "11/23/2002",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label:
      "Ghazi National Institute of Engineering and Sciences, Dera Ghazi Khan",
    "Established Since": "12/24/2021",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Dera Ghazi Khan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Ghazi University, Dera Ghazi Khan",
    "Established Since": "2/11/2012",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Dera Ghazi Khan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Ghulam Ishaq Khan Institute of Engineering Sciences & Technology",
    "Established Since": "7/18/1994",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Abbottabad",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "GIFT University",
    "Established Since": "6/10/2004",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Gujranwala",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label:
      "Global Institute, Lahore [HEC-NOC SUSPENDED] (ADMISSIONS HAVE BEEN STOPPED BY HEC FROM FALL 2016)",
    "Established Since": "1/22/2011",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Gomal University",
    "Established Since": "12/2/1974",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Dera Ismail Khan",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Government College for Women University, Faisalabad",
    "Established Since": "1/5/2013",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Government College for Women University, Sialkot",
    "Established Since": "4/23/2015",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Sialkot",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Government College University, Faisalabad",
    "Established Since": "10/19/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Government College University, Hyderabad",
    "Established Since": "6/17/2019",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Hyderabad",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Government College University, Lahore",
    "Established Since": "9/10/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Government Sadiq College Women University",
    "Established Since": "5/25/2015",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Bahawal Pur",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Greenwich University",
    "Established Since": "2/3/1998",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Habib University",
    "Established Since": "10/8/2012",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Hajvery University",
    "Established Since": "10/2/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Hamdard University",
    "Established Since": "2/22/1992",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Hazara University",
    "Established Since": "5/14/1997",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Mansehra",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Health Services Academy (HSA), Islamabad",
    "Established Since": "5/24/2018",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "HITEC University",
    "Established Since": "11/17/2009",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Ibadat International University, Islamabad",
    "Established Since": "10/8/2021",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Ibn-e-Sina University, Mirpurkhas",
    "Established Since": "7/22/2022",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Mirpur Khas",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "ILMA University",
    "Established Since": "1/12/2004",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Imperial College of Business Studies",
    "Established Since": "4/10/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Indus University",
    "Established Since": "10/20/2004",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Indus Valley School of Art & Architecture",
    "Established Since": "7/27/1994",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Information Technology University of the Punjab",
    "Established Since": "9/10/2012",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Institute for Art and Culture",
    "Established Since": "5/22/2018",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Business Administration",
    "Established Since": "8/17/1994",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Business Management",
    "Established Since": "4/27/1998",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Management and Applied Sciences, Khanewal",
    "Established Since": "11/24/2021",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Khanewal",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Management Science",
    "Established Since": "10/2/2002",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Management Sciences",
    "Established Since": "4/10/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Southern Punjab",
    "Established Since": "8/2/2010",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Institute of Space Technology",
    "Established Since": "4/12/2005",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label:
      "International Institute of Science, Arts and Technology, Gujranwala",
    "Established Since": "7/7/2022",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Gujranwala",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "International Islamic University",
    "Established Since": "3/31/1985",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Iqra National University",
    "Established Since": "4/23/2011",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Iqra University",
    "Established Since": "6/21/2000",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Islamia College Peshawar",
    "Established Since": "3/20/2008",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Islamia University",
    "Established Since": "3/4/1975",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Bahawal Pur",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Isra University",
    "Established Since": "9/27/1997",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Hyderabad",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Jinnah Sindh Medical University",
    "Established Since": "3/21/2013",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Jinnah University for Women",
    "Established Since": "6/2/1998",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Karachi Institute of Economics & Technology",
    "Established Since": "5/24/2001",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label:
      "Karachi Institute of Technology and Entrepreneurship (KITE), Karachi",
    "Established Since": "10/7/2016",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Karachi School of Business and Leadership",
    "Established Since": "3/11/2013",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Karakurum International University",
    "Established Since": "8/28/2002",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Gilgit",
    Province: "Gilgit Baltistan",
    "Recognised University": "Yes",
  },
  {
    label: "KASB Institute of Technology",
    "Established Since": "6/28/2001",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label:
      "Khawaja Freed University of Engineering & Information Technology, Rahim Yar Khan",
    "Established Since": "5/29/2014",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rahim Yar Khan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Khushal Khan Khattak University",
    "Established Since": "5/18/2012",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Karak",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Khyber Medical University",
    "Established Since": "1/13/2007",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Khyber Pakhtunkhwa Agricultural University",
    "Established Since": "2/4/1981",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "King Edward Medical University",
    "Established Since": "2/15/2005",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Kinnaird College for Women",
    "Established Since": "10/25/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Kohat University of Science and Technology",
    "Established Since": "8/30/2001",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Kohat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Kohsar University, Murree",
    "Established Since": "7/2/2020",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore College for Women University",
    "Established Since": "9/10/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore Garrison University",
    "Established Since": "3/19/2014",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore Institute of Science & Technology, Lahore",
    "Established Since": "1/18/2022",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore Leads University",
    "Established Since": "1/22/2001",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore School of Economics",
    "Established Since": "6/16/1997",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lahore University of Management Sciences",
    "Established Since": "3/31/1985",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Lasbela University of Agriculture, Water & Marine Sciences",
    "Established Since": "3/10/2005",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Lasbella",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "Liaquat University of Medical & Health Sciences",
    "Established Since": "1/20/2001",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Jamshoro",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Malir University of Science & Technology, Karachi",
    "Established Since": "4/29/2022",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Mehran University of Engineering & Technology",
    "Established Since": "5/30/1977",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Khairpur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Metropolitan University Karachi",
    "Established Since": "4/5/2016",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Millennium Institute of Technology and Entrepreneurship, Karachi",
    "Established Since": "4/28/2021",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Minhaj University",
    "Established Since": "10/15/2005",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Mir Chakar Khan Rind University of Technology, Dera Ghazi Khan",
    "Established Since": "3/15/2019",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Dera Ghazi Khan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Mir Chakar Khan Rind University, Sibi Balochistan",
    "Established Since": "6/13/2018",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Sibi",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "Mirpur University of Science & Technology",
    "Established Since": "1/18/2008",
    Sector: "Public",
    "Chartered By": "Government of AJK",
    City: "Mirpur",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "Mohi-ud-Din Islamic University",
    "Established Since": "1/18/2000",
    Sector: "Private",
    "Chartered By": "Government of AJK",
    City: "Nerian Sharif",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "Muhammad Ali Jinnah University",
    "Established Since": "5/18/2000",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Muhammad Nawaz Shareef University of Agriculture",
    "Established Since": "9/11/2013",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Muhammad Nawaz Sharif University of Engineering & Technology",
    "Established Since": "5/29/2014",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Multan University of Science & Technology, Multan",
    "Established Since": "11/16/2022",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "MY University",
    "Established Since": "1/1/2013",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Namal Institute, Mainwali",
    "Established Since": "1/25/2019",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Mianwali",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "National College of Arts",
    "Established Since": "3/31/1985",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "National College of Business Administration & Economics",
    "Established Since": "4/10/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "National Defense University",
    "Established Since": "2/5/2007",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "National Skills University, Islamabad",
    "Established Since": "3/15/2018",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "National Textile University",
    "Established Since": "11/15/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "National University of Computer & Emerging Sciences",
    "Established Since": "7/1/2000",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "National University of Medical Sciences",
    "Established Since": "10/31/2015",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "National University of Modern Languages",
    "Established Since": "5/29/2000",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "National University of Sciences & Technology",
    "Established Since": "6/10/1997",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "National University of Technology (NUTECH), Islamabad",
    "Established Since": "2/26/2018",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "NED University of Engineering & Technology",
    "Established Since": "5/30/1977",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Newport Institute of Communications & Economics",
    "Established Since": "5/30/2002",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "NFC Institute of Engineering & Technology",
    "Established Since": "5/8/2012",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Nishtar Medical University, Multan",
    "Established Since": "6/5/2017",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Northern University",
    "Established Since": "11/2/2002",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Nowshehra",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Nur International University",
    "Established Since": "2/26/2015",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label:
      "Pak-Austria Fachhochschule Institute of Applied Sciences and Technology, Haripur",
    "Established Since": "4/1/2019",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Haripur",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Global Institute, Rawat",
    "Established Since": "3/17/2023",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Rawat",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Institute of Development Economics",
    "Established Since": "11/8/2006",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Institute of Engineering & Applied Sciences",
    "Established Since": "3/22/2000",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Institute of Fashion & Design",
    "Established Since": "5/4/2011",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Military Academy",
    "Established Since": "9/18/1959",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Abbottabad",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Pakistan Naval Academy",
    "Established Since": "6/4/1965",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Peoples University of Medical & Health Sciences for Women",
    "Established Since": "12/21/2009",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Nawabshah",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Pir Mehr Ali Shah Arid Agriculture University",
    "Established Since": "5/24/1995",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Preston Institute of Management, Science & Technology",
    "Established Since": "7/31/2001",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },

  {
    label: "Preston University",
    "Established Since": "11/23/2002",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Kohat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Punjab Tianjin University of Technology, Lahore",
    "Established Since": "3/20/2018",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Punjab University of Technology, Rasul-Mandi Bahauddin",
    "Established Since": "5/24/2018",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Mandi Bahauddin",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Qarshi University",
    "Established Since": "5/2/2011",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Quaid-e-Awam University of Engineering, Sciences & Technology",
    "Established Since": "10/29/1996",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Nawabshah",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Quaid-i-Azam University",
    "Established Since": "1/1/1973",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Qurtaba University of Science & Information Technology",
    "Established Since": "8/30/2001",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Rashid Latif Khan University, Lahore",
    "Established Since": "11/24/2021",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Rawalpindi Medical University",
    "Established Since": "5/5/2017",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Rawalpindi Women University, Rawalpindi",
    "Established Since": "8/13/2019",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Riphah International University",
    "Established Since": "10/16/2002",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Salim Habib University (Former Barret Hodgson University), Karachi",
    "Established Since": "8/25/2015",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sardar Bahadur Khan Women University",
    "Established Since": "3/11/2004",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Quetta",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "Sarhad University of Science & Information Technology",
    "Established Since": "8/30/2001",
    Sector: "Private",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Shah Abdul Latif University",
    "Established Since": "12/8/1986",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Khairpur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto City University",
    "Established Since": "3/13/2013",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto Dewan University",
    "Established Since": "3/7/2013",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto University",
    "Established Since": "10/6/2009",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Upper Dir",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto University of Veterinary & Animal Sciences",
    "Established Since": "9/13/2012",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Nawabshah",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
    "Established Since": "11/12/2010",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Nawabshah",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Benazir Bhutto Women University",
    "Established Since": "2/1/2005",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Mohtarma Benazir Bhutto Medical University",
    "Established Since": "10/18/2008",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Larkana",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Zulfikar Ali Bhutto Institute of Science & Technology",
    "Established Since": "10/25/1995",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Zulfiqar Ali Bhutto Medical University",
    "Established Since": "3/21/2013",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Shaheed Zulfiqar Ali Bhutto University of Law",
    "Established Since": "3/1/2013",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Shifa Tameer-e-Millat University",
    "Established Since": "3/6/2012",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Shuhada-e-Army Public School University of Technology, Nowshera",
    "Established Since": "5/14/2015",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Nowshehra",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Sindh Agriculture University, Tandojam",
    "Established Since": "5/30/1977",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Hyderabad",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sindh Institute of Management & Technology",
    "Established Since": "3/18/2015",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sindh Institute of Medical Sciences",
    "Established Since": "6/29/2009",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sindh Madresatul Islam University",
    "Established Since": "12/22/2011",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sir Syed (CASE) Institute of Technology, Islamabad",
    "Established Since": "5/24/2018",
    Sector: "Private",
    "Chartered By": "Government of Pakistan",
    City: "Islamabad",
    Province: "Islamabad Capital Territory",
    "Recognised University": "Yes",
  },
  {
    label: "Sir Syed University of Engineering & Technology",
    "Established Since": "10/25/1995",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sohail University, Karachi",
    "Established Since": "5/9/2018",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Sukkur Institute of Business Administration",
    "Established Since": "4/24/2006",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Sukkur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Textile Institute of Pakistan",
    "Established Since": "4/21/2001",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "Thal University, Bhakkar",
    "Established Since": "2/9/2022",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Bhakkar",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "The Bolan University of Medical and Health Sciences, Quetta",
    "Established Since": "12/11/2017",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Quetta",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "The Grand Asian University, Sialkot",
    "Established Since": "12/24/2021",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Sialkot",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "The Green International University, Lahore",
    "Established Since": "6/4/2020",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "The Nazeer Hussain University",
    "Established Since": "5/30/2003",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "The Shaikh Ayaz University, Shikarpur Sindh",
    "Established Since": "6/7/2018",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Shikarpur",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "The Superior University",
    "Established Since": "6/16/2004",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "The University of Agriculture, D. I. Khan",
    "Established Since": "3/7/2018",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Dera Ismail Khan",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "The University of Faisalabad",
    "Established Since": "10/2/2003",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "The Women University",
    "Established Since": "8/2/2010",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Times Institute, Multan",
    "Established Since": "9/16/2020",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Multan",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "UIT University, Karachi",
    "Established Since": "5/28/2018",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of Agriculture",
    "Established Since": "5/24/1973",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Faisalabad",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Art and Culture, Jamshoro",
    "Established Since": "4/17/2018",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Jamshoro",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of Azad Jammu & Kashmir",
    "Established Since": "12/8/1985",
    Sector: "Public",
    "Chartered By": "Government of AJK",
    City: "Muzaffarabad",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "University of Balochistan",
    "Established Since": "7/1/1996",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Quetta",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "University of Baltistan, Skardu",
    "Established Since": "8/25/2017",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Skardu",
    Province: "Gilgit Baltistan",
    "Recognised University": "Yes",
  },
  {
    label: "University of Buner",
    "Established Since": "11/30/2016",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Bunair",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Central Punjab",
    "Established Since": "4/10/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Chakwal, Chakwal",
    "Established Since": "1/9/2020",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Chakwal",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Chenab, Gujrat",
    "Established Since": "10/1/2021",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Gujrat",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Child Health Sciences, Lahore",
    "Established Since": "6/30/2021",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Chitral",
    "Established Since": "5/2/2019",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Chitral",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Education",
    "Established Since": "9/10/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },

  {
    label: "University of Engineering & Technology",
    "Established Since": "4/11/1974",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Engineering & Technology (UET), Mardan",
    "Established Since": "3/7/2018",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Mardan",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Engineering & Technology, Taxila",
    "Established Since": "12/7/1994",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Engineering and Applied Sciences, Swat",
    "Established Since": "9/21/2021",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Swat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of FATA",
    "Established Since": "5/22/2013",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Kohat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Gujrat",
    "Established Since": "2/23/2004",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Gujrat",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Gwadar",
    "Established Since": "9/20/2018",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Gawadar",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "University of Haripur",
    "Established Since": "9/20/2012",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Haripur",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Health Sciences",
    "Established Since": "9/28/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Home Economics, Lahore",
    "Established Since": "2/13/2017",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Jhang",
    "Established Since": "6/16/2015",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Jhang",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Karachi",
    "Established Since": "12/28/1972",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of Kotli",
    "Established Since": "1/2/2014",
    Sector: "Public",
    "Chartered By": "Government of AJK",
    City: "Kotli",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "University of Lahore",
    "Established Since": "10/2/2002",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Lakki Marwat",
    "Established Since": "2/26/2018",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Lakki Marwat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Loralai",
    "Established Since": "9/27/2012",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Loralai",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "University of Malakand",
    "Established Since": "10/27/2001",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Malakand",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Management & Technology",
    "Established Since": "6/16/2004",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Mianwali",
    "Established Since": "12/13/2019",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Mianwali",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Modern Sciences, Tando Muhammad Khan",
    "Established Since": "5/4/2018",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Tando Muhammad  Khan",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of Narowal",
    "Established Since": "3/20/2018",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Narowal",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Okara",
    "Established Since": "2/23/2016",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Okara",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Peshawar",
    "Established Since": "6/4/1965",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Peshawar",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Poonch",
    "Established Since": "3/25/2014",
    Sector: "Public",
    "Chartered By": "Government of AJK",
    City: "Poonch",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "University of Sahiwal",
    "Established Since": "6/16/2015",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Sahiwal",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Sargodha",
    "Established Since": "11/16/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Sargodha",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Science & Technology",
    "Established Since": "8/6/2005",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Bannu",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Sialkot, Sialkot",
    "Established Since": "3/20/2018",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Sialkot",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Sindh",
    "Established Since": "12/28/1972",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Mirpur Khas",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of South Asia",
    "Established Since": "7/9/2005",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Sufism and Modern Sciences, Bhitshah Sindh",
    "Established Since": "5/22/2019",
    Sector: "Public",
    "Chartered By": "Government of Sindh",
    City: "Bhit Shah",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
  {
    label: "University of Swabi",
    "Established Since": "7/3/2012",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Swabi",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Swabi for Women",
    "Established Since": "1/1/2012",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Swabi",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of Swat",
    "Established Since": "7/7/2010",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Swat",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "University of the Punjab",
    "Established Since": "5/16/1973",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Turbat",
    "Established Since": "6/28/2012",
    Sector: "Public",
    "Chartered By": "Government of Balochistan",
    City: "Turbat",
    Province: "Balochistan",
    "Recognised University": "Yes",
  },
  {
    label: "University of Veterinary & Animal Sciences",
    "Established Since": "6/8/2002",
    Sector: "Public",
    "Chartered By": "Government of Punjab",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "University of Wah",
    "Established Since": "7/8/2009",
    Sector: "Private",
    "Chartered By": "Government of Punjab",
    City: "Rawalpindi",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Virtual University of Pakistan",
    "Established Since": "9/11/2002",
    Sector: "Public",
    "Chartered By": "Government of Pakistan",
    City: "Lahore",
    Province: "Punjab",
    "Recognised University": "Yes",
  },
  {
    label: "Women University Mardan",
    "Established Since": "1/1/2016",
    Sector: "Public",
    "Chartered By": "Government of Khyber Pakhtunkhwa",
    City: "Mardan",
    Province: "Khyber Pakhtunkhwa",
    "Recognised University": "Yes",
  },
  {
    label: "Women University of Azad Jammu & Kashmir",
    "Established Since": "3/25/2014",
    Sector: "Public",
    "Chartered By": "Government of AJK",
    City: "Bagh",
    Province: "Azad Jammu & Kashmir",
    "Recognised University": "Yes",
  },
  {
    label: "Zia-ud-Din University",
    "Established Since": "12/13/2005",
    Sector: "Private",
    "Chartered By": "Government of Sindh",
    City: "Karachi",
    Province: "Sindh",
    "Recognised University": "Yes",
  },
];

export default data;
